---
- name: stop postgres postgres service
  systemd:
    name: postgresql-14.service
    state: stopped

- name: clear postgres directory
  file:
    path: /var/lib/pgsql/14/data
    state: absent

- name: create empty postgres data directory
  file:
    path: /var/lib/pgsql/14/data
    state: directory
    owner: postgres
    group: postgres
    mode: "0700"

- name: get postgres dump
  command: "pg_basebackup -X stream -h 192.168.56.110 -U repl -p 5432 -D /var/lib/pgsql/14/data/ -R -P"
  become: true
  become_user: postgres

- name: start pgsql service
  systemd:
    name: postgresql-14.service
    enabled: true
    state: started

- name: enable pg_stat_statements
  become: true
  become_user: postgres
  community.postgresql.postgresql_ext:
    name: pg_stat_statements
    db: postgres
    state: present
