---
- name: add repo
  dnf:
    name: centos-release-gluster9
    state: present

- name: install packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - glusterfs
    - glusterfs-libs
    - glusterfs-server

- name: change hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.56.110 db
      192.168.56.109 replica
      192.168.56.111 app1
      192.168.56.112 app2

- name: start gluster service
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - glusterfsd.service
    - glusterd.service
#- name: create directory
#  file:
#    path: /home/vagrant/volume1
#    state: directory
